# Main configuration for species and data paths

species: "Human"
tax_id: 9606

ref_genome: "hg38"
anc_alleles: 
  path: "resources/data/Human/ancestral_alleles/homo_sapiens_ancestor_GRCh38"
  prefix: "homo_sapiens_ancestor_chr"

genome_annotation: "resources/data/Human/annotation/Human.gtf.gz"
gene2go: "resources/data/Human/annotation/gene2go.gz"

hwe_pvalue: 0.001

rmsk: "resources/data/Human/repeats/hg38.rmsk.autosomes.bed"
seg_dup: "resources/data/Human/repeats/hg38.seg.dups.autosomes.bed"
sim_rep: "resources/data/Human/repeats/hg38.simple.repeats.autosomes.bed"

ploidy: 2

# Population definitions
populations:
  - ACB
  - ASW
  - BEB
  - CDX
  - CEU
  - CHB
  - CHS
  - CLM
  - ESN
  - FIN
  - GBR
  - GIH
  - GWD
  - IBS
  - ITU
  - JPT
  - KHV
  - LWK
  - MSL
  - MXL
  - PEL
  - PJL
  - PUR
  - STU
  - TSI
  - YRI

# Data file configuration
# Base folder for resources
data_folder: "resources/data/Human/1KG"
  
# VCF file naming convention: {file_prefix}chr{chr_name}{file_suffix}
vcf_prefix: "full_chr"
vcf_suffix: ".vcf.gz"
    
# Sample metadata file
metadata: "resources/data/Human/1KG/samples.txt"
  
# Chromosome range to analyze
chromosomes:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22

selscan_config: "config/selscan.yaml"
betascan_config: "config/betascan.yaml"
dadi_config: "config/dadi-cli.yaml"
scikit_allel_config: "config/scikit-allel.yaml"
