# scikit-allel analysis configuration

# Within-population statistics
wp_stats:
  - windowed_tajima_d   
  - moving_tajima_d  

# Windowed Tajima's D
wtjd_window_sizes: [100_000]
wtjd_step_size_ratios: [1]

# Moving Tajima's D
mtjd_window_sizes: [100]
mtjd_step_size_ratios: [1]

# Cross-population statistics 
xp_stats:
  - delta_moving_tajima_d

# Delta Tajima's D
dtjd_window_sizes: [100]
dtjd_step_size_ratios: [1]

# Statistical thresholds
# Top proportion for outlier identification
top_proportion: 0.05

# Manhattan plot settings 
manhattan_plot_width: 640
manhattan_plot_height: 240
manhattan_plot_color1: "#56B4E9"
manhattan_plot_color2: "#F0E442"
